### ISSUE TITLE
New images builds fail

### ISSUE THREAD

**Issue by anarion80** [zmkfirmware/zmk-docker#144] opened 2023-10-21 14:13 UTC
Looks like last successful image build was over 4 months ago:
https://github.com/zmkfirmware/zmk-docker/actions

Please fix it so we can use the latest features when using docker 🙏

**Comment by petejohanson** [comment] 2023-10-21 18:02
Looks like this issue we're hitting: https://github.com/zephyrproject-rtos/zephyr/issues/60213

I just cherry picked the Python fix from https://github.com/zephyrproject-rtos/zephyr/pull/60774 into our Zephyr branch, hopefully that addresses that regression and the next build will be good.

In the meantime, definitely favor using the `stable` tag for the images as pushed to Docker Hub to get a solid reliable build of this.

**Comment by petejohanson** [comment] 2023-10-21 18:51
@anarion80 That seems to have done the trick. Closing this for now, but feel free to re-open if you still have issues. Thanks!

**Closed as completed by petejohanson** 2023-10-21 18:51 UTC

**Comment by anarion80** [comment] 2023-10-22 11:02
Thanks!
